#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXX)
tmpdir=$(mktemp -d /tmp/resource-in-source.XXXXX)

cat > $payload <&0

# fetch latest for given source (exclude version)
cat $payload | jq '{source}' | $(dirname $0)/in $tmpdir

ref=$(jq -r '.version.ref // "HEAD~1"' < $payload)

cd $tmpdir

branch=$(git rev-parse --abbrev-ref HEAD | jq -R .)

git log --reverse --oneline --no-abbrev-commit ${ref}..HEAD | \
  cut -d' ' -f1 | \
  jq -R '.' | \
  jq -s "map({ref: .})" >&3
