#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload="$(cat <&0)"

unknown_keys=$(jq --slurpfile schema "$(dirname $0)/out_schema.json" '(.params // [] | keys_unsorted) - ($schema[0] | keys_unsorted)' <<< "$payload")

if jq --exit-status 'length > 0' <<< "$unknown_keys" &>/dev/null; then
    echo "Found unknown keys in put params:"
    jq '.[]' <<< "$unknown_keys"
    exit 1
fi

load_pubkey "$payload"
configure_https_tunnel "$payload"
configure_git_ssl_verification "$payload"
configure_credentials "$payload"

uri=$(jq -r '.source.uri // ""' <<< "$payload")
branch=$(jq -r '.source.branch // ""' <<< "$payload")
git_config_payload=$(jq -r '.source.git_config // []' <<< "$payload")
repository=$(jq -r '.params.repository // ""' <<< "$payload")
tag=$(jq -r '.params.tag // ""' <<< "$payload")
tag_prefix=$(jq -r '.params.tag_prefix // ""' <<< "$payload")
rebase=$(jq -r '.params.rebase // false' <<< "$payload")
merge=$(jq -r '.params.merge // false' <<< "$payload")
returning=$(jq -r '.params.returning // "merged"' <<< "$payload")
force=$(jq -r '.params.force // false' <<< "$payload")
only_tag=$(jq -r '.params.only_tag // false' <<< "$payload")
annotation_file=$(jq -r '.params.annotate // ""' <<< "$payload")
notes_file=$(jq -r '.params.notes // ""' <<< "$payload")
override_branch=$(jq -r '.params.branch // ""' <<< "$payload")
# useful for pushing to special ref types like refs/for in gerrit.
refs_prefix=$(jq -r '.params.refs_prefix // "refs/heads"' <<< "$payload")

configure_git_global "${git_config_payload}"

if [ -z "$uri" ]; then
  echo "invalid payload (missing uri)"
  exit 1
fi

setup_github_app_credentials

if [ -z "$branch" ] && [ "$only_tag" != "true" ] && [ -z "$override_branch" ]; then
  echo "invalid payload (missing branch)"
  exit 1
fi

if [ -z "$repository" ]; then
  echo "invalid payload (missing repository)"
  exit 1
fi

if [ "$merge" = "true" ] && [ "$rebase" = "true" ]; then
  echo "invalid push strategy (either merge or rebase can be set, but not both)"
  exit 1
fi

cd $source

if [ -n "$tag" ] && [ ! -f "$tag" ]; then
  echo "tag file '$tag' does not exist"
  exit 1
fi

if [ -n "$annotation_file" ] && [ ! -f $annotation_file ]; then
  echo "annotation file '$annotation_file' does not exist"
  exit 1
fi

forceflag=""
if [ $force = "true" ]; then
  forceflag="--force"
fi

if [ -n "$override_branch" ]; then
  echo "Override $branch with $override_branch"
  branch=$override_branch
fi

tag_name=""
if [ -n "$tag" ]; then
  tag_name="$(cat $tag)"
fi

annotate=""
if [ -n "$annotation_file" ]; then
  annotate=" -a -F $source/$annotation_file"
fi

cd $repository

tag() {
  if [ -n "$tag_name" ]; then
    git tag -f "${tag_prefix}${tag_name}" $annotate
  fi
}

push_src_and_tags() {
  git push --tags push-target HEAD:$refs_prefix/$branch $forceflag
}

push_tags() {
  git push --tags push-target $forceflag
}

add_and_push_notes() {
  if [ -n "$notes_file" ]; then
    git notes add -F "../${notes_file}"
    git push push-target refs/notes/*
  fi
}

push_with_result_check() {
  # oh god this is really the only way to do this
  result_file=$(mktemp $TMPDIR/git-result.XXXXXX)

  echo 0 > $result_file

  {
    tag 2>&1 && push_src_and_tags 2>&1 && add_and_push_notes 2>&1 || {
      echo $? > $result_file
    }
  } | tee $TMPDIR/push-failure

  # despite what you may think, the embedded cat does not include the
  # trailing linebreak
  #
  # $() appears to trim it
  #
  # someone rewrite this please
  #
  # pull requests welcome
  if [ "$(cat $result_file)" = "0" ]; then
    echo "pushed"
    eval "$1=0"
    return
  fi

  # failed for reason other than non-fast-forward / fetch-first
  if ! grep -q '\[rejected\]\|\[remote rejected\].*cannot lock ref' $TMPDIR/push-failure; then
    echo "failed with non-rebase error"
    eval "$1=1"
    return
  fi

  eval "$1=2"
}

git remote add push-target $uri
commit_to_push=$(git rev-parse HEAD)

if [ "$only_tag" = "true" ]; then
  tag
  push_tags
elif [ "$merge" = "true" ]; then
  while true; do
    echo "merging..."

    git reset --hard $commit_to_push

    git fetch push-target "refs/notes/*:refs/notes/*"
    git pull --no-edit push-target $branch

    result="0"
    push_with_result_check result
    if [ "$result" = "0" ]; then
      break
    elif [ "$result" = "1" ]; then
      exit 1
    fi

    echo "merging and trying again..."
  done
elif [ "$rebase" = "true" ]; then
  while true; do
    echo "rebasing..."

    git fetch push-target "refs/notes/*:refs/notes/*"
    git pull --rebase=merges push-target $branch

    result="0"
    push_with_result_check result
    if [ "$result" = "0" ]; then
      break
    elif [ "$result" = "1" ]; then
      exit 1
    fi

    echo "rebasing and trying again..."
  done
else
  tag
  push_src_and_tags
  add_and_push_notes
fi

if [ "$merge" = "true" ] && [ "$returning" = "unmerged" ]; then
  version_ref="$(echo "$commit_to_push" | jq -R .)"
else
  version_ref="$(git rev-parse HEAD | jq -R .)"
fi

if [ -n "$override_branch" ]; then
  jq -n "{
    version: {branch: $(echo $override_branch | jq -R .), ref: $version_ref},
    metadata: $(git_metadata)
  }" >&3
else
  jq -n "{
    version: {ref: $version_ref},
    metadata: $(git_metadata)
  }" >&3
fi
