#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXX)

cat > $payload <&0

load_pubkey $payload

branch=$(jq -r '.branch // ""' < $payload)
remote=$(jq -r '.remote // ""' < $payload)

if [ -z "$branch" ]; then
  echo "invalid payload (missing branch):" >&2
  cat $payload >&2
  exit 1
fi

if [ -z "$remote" ]; then
  echo "invalid payload (missing remote):" >&2
  cat $payload >&2
  exit 1
fi

cd $source

git remote add push-target $remote 1>&2
git push push-target HEAD:refs/heads/$branch 1>&2

jq -n "{
  uri: $(git ls-remote --get-url origin | jq -R .),
  branch: $(jq '.branch' < $payload),
  ref: $(git rev-parse HEAD | jq -R .),
  private_key: $(jq '.private_key' < $payload)
}" >&3
