#!/bin/bash

set -e -u -x

# avoid importing fixture key into real keyring.
rm -rf /tmp/gpghome
mkdir /tmp/gpghome
export GNUPGHOME=/tmp/gpghome

gpg --import private.key

rm -rf fixture_repo.git

git init --bare fixture_repo.git
rm fixture_repo.git/hooks/*.sample

rm -rf repo
git clone fixture_repo.git repo
cd repo

git \
  -c user.name='test' \
  -c user.email='test@example.com' \
  commit -q --allow-empty -m "init"

echo x >> some-file
git add some-file

echo enter passphrase: secret123

git \
  -c user.name='test' \
  -c user.email='test@example.com' \
  commit -q --gpg-sign=B0F5F8EF \
  -m "commit $(wc -l some-file) Test message"

git push -u origin master

cd ..
rm -rf repo
